### ISSUE TITLE
Failed action or assertion on an element not initially in the page

### ISSUE THREAD

**Issue by zzebastien** [rochdev/tinto#10]
When trying to do an assertion or an action on an element not initially on page (example: dialog), the error is returned:

```
var dialog = tinto.page.find('acq-dialog').first().as(Dialog);
dialog.ok.click();

Error returned:
ElementNotFoundError: Element could not be found
```

**Comment by rochdev** [comment]
This is the expected behaviour but it should be more descriptive as described in #9

**Comment by rochdev** [comment]
The error persists even if the element has become available
