### ISSUE TITLE
No support for 'And' and 'But' in tinto scenario

### ISSUE THREAD

**Issue by zzebastien** [rochdev/tinto#16]
Given, When, Then are supported.
'And' and 'But' are not supported.

See https://github.com/cucumber/cucumber/wiki/Given-When-Then

**Comment by rochdev** [comment]
This is actually not supported by cucumber-js (see https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/support_code/library.js at the end of the file)

Future versions of Tinto might have its own syntax abstracted from existing libraries but right now it tries to simply wrap around cucumber-js.
