### ISSUE TITLE
Improve error "ElementNotFoundError: Element could not be found"

### ISSUE THREAD

**Issue by zzebastien** [rochdev/tinto#9]
Can we have the element name and locator reference in the error message ?

**Comment by rochdev** [comment]
@zzebastien The element name would be impossible since you cannot grab the element to get its name. Would something along the lines of `No element matching selector "button[type=submit]" could be found under [Panel:3038f690-a03f-4b5e-b854-daabcde57804] at index 0` make sense?

**Comment by zzebastien** [comment]
It's perfect, having the selector in the error message is what is expected.
